
const foods = [
    { name: "زرشک پلو", options: null, tags: ["برنجی"] },
    { name: "عدس پلو", options: null, tags: ["برنجی"] },
    { name: "برنج با مرغ ماستی", options: null, tags: ["برنجی"] },
    { name: "آب گوشت", options: null, tags: ["برنجی", "نانی"] },
    { name: "قرمه سبزی", options: null, tags: ["برنجی"] },
    { name: "شوید پلو", options: null, tags: ["برنجی"] },
    {
      name: "دمپختک",
      options: ["ساده", "لوبیا چیتی"],
      tags: ["برنجی"],
    },
    { name: "سالاد الویه", options: null, tags: ["نانی"] },
    { name: "فلافل", options: null, tags: ["نانی"] },
    { name: "اسنک", options: null, tags: ["نانی"] },
    { name: "پیتزا", options: null, tags: ["نانی"] },
    { name: "عدس", options: null, tags: ["نانی"] },
    { name: "آش", options: ["رشته", "ماست"], tags: ["نانی"] },
    { name: "سوپ", options: null, tags: ["نانی"] },
    { name: "نان", options: ["شلشلو", "باتو"], tags: ["نانی"] },
    { name: "نخود", options: null, tags: ["نانی"] },
    {
      name: "تخم مرغ و سیب زمینی آب پز",
      options: null,
      tags: ["نانی"],
    },
    { name: "برنج با مرخ سوخاری", options: null, tags: ["برنجی"] },
    {
      name: "کوبیده",
      options: ["خالی", "با برنج"],
      tags: ["برنجی", "نانی"],
    },
    {
      name: "کنجه",
      options: ["خالی", "با برنج"],
      tags: ["برنجی", "نانی"],
    },
    { name: "برنج ماهی گردو", options: null, tags: ["برنجی"] },
    { name: "ماکارونی", options: ["مرغ", "سویا"], tags: ["ماکارونی"] },
    { name: "لوبیا ماهی", options: null, tags: ["نانی"] },
    { name: "سمبوسه", options: null, tags: ["نانی"] },
    { name: "املت", options: null, tags: ["نانی"] },
    {
      name: "تخم مرغ",
      options: ["ساده", "آب پز", "هویج", "قارچ", "شوید", "میگو"],
      tags: ["نانی"],
    },
    { name: "ماست", options: ["کدو", "قارچ", "نان"], tags: ["نانی"] },
    { name: "بادمجان با گوجه", options: null, tags: ["نانی"] },
    { name: "حلیم بادمجان", options: null, tags: ["نانی"] },
    { name: "کوکو", options: null, tags: ["نانی"] },
  ];
                   
export default foods;